name: JS

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build frontend (Compose Web)
        run: ./gradlew -Ponotoliy.github.username=${{ github.actor }} -Ponotoliy.github.token=${{ secrets.GITHUB_TOKEN }} build --no-daemon

      - name: Upload frontend artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: app/js

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/opposite-treasure-kmp-js:$GITHUB_REF_NAME  -f app/js/Dockerfile app/js

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/opposite-treasure-kmp-js:$GITHUB_REF_NAME