name: Build Desktop

on:
  release:
    types:
      - created

jobs:
  build-desktop:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
       
      - name: Install WiX Toolset
        run: choco install wixtoolset --no-progress -y

      - name: Build EXE & MSI
        run: ./gradlew :app:desktop:packageReleaseExe :app:desktop:packageReleaseMsi
        env:
          ONOTOLIY_GITHUB_USERNAME: ${{ github.actor }}
          ONOTOLIY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload EXE & MSI to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app/desktop/build/compose/binaries/main-release/exe/*.exe
            app/desktop/build/compose/binaries/main-release/msi/*.msi    
