name: Build Web

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
       
      - name: Build Web
        run: ./gradlew :app:js:jsBrowserDistribution
        env:
          ONOTOLIY_GITHUB_USERNAME: ${{ github.actor }}
          ONOTOLIY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive Web
        run: |
          cd app/js/build/dist/js/productionExecutable
          zip -r ../../../frontend-web-${{ github.ref_name }}.zip .
        shell: bash

      - name: Upload Web to Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/frontend-web-${{ github.ref_name }}.zip

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/opposite-treasure-kmp-js:$GITHUB_REF_NAME  -f app/js/Dockerfile app/js

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}/opposite-treasure-kmp-js:$GITHUB_REF_NAME       

